# Generated by Django 6.1 on 2026-08-31 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='Descrição')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Status da causa',
                'verbose_name_plural': 'Status das causas',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='LegalCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('area_juridica', models.CharField(blank=True, max_length=100, verbose_name='Área jurídica')),
                ('descricao', models.TextField(verbose_name='Descrição da causa')),
                ('numero_processo', models.CharField(blank=True, max_length=50, verbose_name='Número do processo')),
                ('vara', models.CharField(blank=True, max_length=150, verbose_name='Vara')),
                ('comarca', models.CharField(blank=True, max_length=150, verbose_name='Comarca')),
                ('data_abertura', models.DateField(auto_now_add=True, verbose_name='Data de abertura')),
                ('data_encerramento', models.DateField(blank=True, null=True, verbose_name='Data de encerramento')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='casos', to='clients.client', verbose_name='Cliente')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='casos', to='cases.casestatus', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Caso jurídico',
                'verbose_name_plural': 'Casos jurídicos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
