# Generated by Django 6.1 on 2026-09-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_casemovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalcase',
            name='classe_processual',
            field=models.CharField(blank=True, max_length=255, verbose_name='Classe processual'),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='classe_processual_codigo',
            field=models.CharField(blank=True, max_length=30, verbose_name='Código da classe processual'),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='data_ajuizamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de ajuizamento'),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='datajud_consultado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última consulta ao DataJud'),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='grau',
            field=models.CharField(blank=True, max_length=30, verbose_name='Grau'),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='orgao_julgador_codigo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Código do órgão julgador'),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='sistema_processual',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sistema processual'),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='tribunal',
            field=models.CharField(blank=True, max_length=30, verbose_name='Tribunal'),
        ),
    ]
