# Generated by Django 6.1 on 2026-09-24 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_legalcase_classe_processual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalcase',
            name='orgao_julgador_nome',
            field=models.CharField(blank=True, max_length=255, verbose_name='Órgão julgador'),
        ),
    ]
