# Generated by Django 6.1 on 2026-08-31 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_casemovement'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequiredDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Documento')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='Descrição')),
                ('recebido', models.BooleanField(default=False, verbose_name='Recebido')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('recebido_em', models.DateTimeField(blank=True, null=True, verbose_name='Recebido em')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_necessarios', to='cases.legalcase', verbose_name='Caso')),
            ],
            options={
                'verbose_name': 'Documento necessário',
                'verbose_name_plural': 'Documentos necessários',
                'ordering': ['recebido', 'nome'],
            },
        ),
    ]
