# Generated by Django 6.1 on 2026-09-20 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaevent',
            name='google_calendar_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='ID do calendário no Google'),
        ),
        migrations.AddField(
            model_name='agendaevent',
            name='google_event_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='ID do evento no Google'),
        ),
        migrations.AddField(
            model_name='agendaevent',
            name='google_event_link',
            field=models.URLField(blank=True, max_length=500, verbose_name='Link do evento no Google'),
        ),
        migrations.AddField(
            model_name='agendaevent',
            name='google_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sincronizado com Google em'),
        ),
    ]
