# Generated by Django 6.1 on 2026-09-20 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_agendaevent_google_calendar_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalendarConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_email', models.EmailField(blank=True, max_length=254, verbose_name='Conta Google')),
                ('calendar_id', models.CharField(default='primary', max_length=255, verbose_name='Calendário')),
                ('refresh_token', models.TextField(verbose_name='Refresh token')),
                ('scopes', models.TextField(blank=True, verbose_name='Escopos autorizados')),
                ('conectado_em', models.DateTimeField(auto_now_add=True, verbose_name='Conectado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_calendar_connection', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Conexão com Google Calendar',
                'verbose_name_plural': 'Conexões com Google Calendar',
            },
        ),
    ]
