# Generated by Django 6.1 on 2026-09-20 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_googlecalendarconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaevent',
            name='google_sync_status',
            field=models.CharField(choices=[('not_synced', 'Não sincronizado'), ('synced', 'Sincronizado'), ('removed', 'Removido do Google'), ('error', 'Erro de sincronização')], db_index=True, default='not_synced', max_length=20, verbose_name='Status da sincronização Google'),
        ),
    ]
