# Generated by Django 6.1 on 2026-09-21 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_agendaevent_google_sync_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaevent',
            name='concluido_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Concluído em'),
        ),
        migrations.AddField(
            model_name='agendaevent',
            name='concluido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_concluidos', to=settings.AUTH_USER_MODEL, verbose_name='Concluído por'),
        ),
        migrations.AddField(
            model_name='agendaevent',
            name='resultado',
            field=models.TextField(blank=True, help_text='Resultado, providência ou observação referente à realização do compromisso.', verbose_name='Resultado'),
        ),
        migrations.AddField(
            model_name='agendaevent',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Agendado'), ('confirmed', 'Confirmado'), ('completed', 'Concluído'), ('not_completed', 'Não realizado'), ('canceled', 'Cancelado'), ('rescheduled', 'Reagendado')], db_index=True, default='scheduled', max_length=20, verbose_name='Status'),
        ),
    ]
