# Generated by Django 6.1 on 2026-09-22 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_agendaevent_concluido_em_agendaevent_concluido_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlecalendarconnection',
            name='ultima_sincronizacao_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última sincronização'),
        ),
    ]
