# Generated by Django 6.1 on 2026-09-20 00:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('agenda', 'Agenda'), ('deadline', 'Prazo'), ('document', 'Documento'), ('case', 'Caso jurídico'), ('system', 'Sistema')], db_index=True, default='system', max_length=20, verbose_name='Tipo')),
                ('nivel', models.CharField(choices=[('info', 'Informação'), ('attention', 'Atenção'), ('urgent', 'Urgente')], db_index=True, default='info', max_length=20, verbose_name='Nível')),
                ('titulo', models.CharField(max_length=160, verbose_name='Título')),
                ('mensagem', models.TextField(blank=True, verbose_name='Mensagem')),
                ('url_destino', models.CharField(blank=True, max_length=500, verbose_name='URL de destino')),
                ('chave', models.CharField(blank=True, help_text='Identificador opcional utilizado para impedir notificações automáticas duplicadas.', max_length=255, null=True, unique=True, verbose_name='Chave única')),
                ('lida', models.BooleanField(db_index=True, default=False, verbose_name='Lida')),
                ('lida_em', models.DateTimeField(blank=True, null=True, verbose_name='Lida em')),
                ('criada_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criada em')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ('-criada_em', '-pk'),
                'indexes': [models.Index(fields=['usuario', 'lida', '-criada_em'], name='notif_user_read_date_idx')],
            },
        ),
    ]
